AC2DM_URL = "https://android.googleapis.com/gcm/send"
ANDROID_HEADER_AUTH = "key=AIzaSyAhjL9dQT44iLRIEV88ZufVHlBBSach774"
SAMPLE_ANDROID_REGISTRATION_ID = "APA91bFJfMfqqtyjoGAOEzVx8YGxsiXbIuRS8SmCfiFBSIslmlBjRKin4pDTiYtr6ie7OELlsTgmMz4oege7Zf8"
